
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));
const Quests = lazy(() => import("./pages/Quests.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/pricing", element: <UserGuard><Pricing /></UserGuard>},
	{ path: "/quests", element: <UserGuard><Quests /></UserGuard>},

];
